In [6]:
path = 'https://raw.githubusercontent.com/tec03/Datasets/main/datasets/fpEg1.csv'

In [7]:
#pip install pandas

In [8]:
import pandas as pd

In [9]:
df = pd.read_csv(path, 
                 header = None)
df

   0  1  2  3  4    5    6    7
0  a  c  d  f  g    i    m    p
1  a  b  c  f  l    m    o  NaN
2  b  f  h  j  o  NaN  NaN  NaN
3  b  c  k  s  p  NaN  NaN  NaN
4  a  c  e  f  i    p    m    n

In [10]:
## Data pre-processing

In [15]:
transaction = []
for i in range(0, df.shape[0]): #for each row
    for j in range(0, df.shape[1]): # for each column
        transaction.append(df.values[i][j]) # adding each element to the empty set
transaction

['a',
 'c',
 'd',
 'f',
 'g',
 'i',
 'm',
 'p',
 'a',
 'b',
 'c',
 'f',
 'l',
 'm',
 'o',
 nan,
 'b',
 'f',
 'h',
 'j',
 'o',
 nan,
 nan,
 nan,
 'b',
 'c',
 'k',
 's',
 'p',
 nan,
 nan,
 nan,
 'a',
 'c',
 'e',
 'f',
 'i',
 'p',
 'm',
 'n']

In [16]:
ndf = pd.DataFrame(transaction,
                   columns = ['items']
                  )
ndf.head(2)

  items
0     a
1     c

In [21]:
pip install numpy

Requirement already satisfied: numpy in /srv/conda/envs/notebook/lib/python3.7/site-packages (1.21.6)
Note: you may need to restart the kernel to use updated packages.

In [22]:
import numpy as np

In [23]:
transaction = np.array(transaction)
transaction

array(['a', 'c', 'd', 'f', 'g', 'i', 'm', 'p', 'a', 'b', 'c', 'f', 'l',
       'm', 'o', 'nan', 'b', 'f', 'h', 'j', 'o', 'nan', 'nan', 'nan', 'b',
       'c', 'k', 's', 'p', 'nan', 'nan', 'nan', 'a', 'c', 'e', 'f', 'i',
       'p', 'm', 'n'], dtype='<U32')

In [24]:
ndf = pd.DataFrame(transaction,
                   columns = ['items']
                  )
ndf.head(2)

  items
0     a
1     c

In [29]:
to_be_deleted = ndf[ndf['items']=='nan'].index
to_be_deleted

Int64Index([15, 21, 22, 23, 29, 30, 31], dtype='int64')

In [30]:
ndf.drop(to_be_deleted,
         inplace = True)
ndf ['count'] = 1
ndf

   items  count
0      a      1
1      c      1
2      d      1
3      f      1
4      g      1
5      i      1
6      m      1
7      p      1
8      a      1
9      b      1
10     c      1
11     f      1
12     l      1
13     m      1
14     o      1
16     b      1
17     f      1
18     h      1
19     j      1
20     o      1
24     b      1
25     c      1
26     k      1
27     s      1
28     p      1
32     a      1
33     c      1
34     e      1
35     f      1
36     i      1
37     p      1
38     m      1
39     n      1

In [34]:
df_table = ndf.groupby('items').sum().sort_values('count',
                                                  ascending = False).reset_index()
df_table

   items  count
0      c      4
1      f      4
2      a      3
3      b      3
4      p      3
5      m      3
6      o      2
7      i      2
8      h      1
9      j      1
10     k      1
11     l      1
12     g      1
13     n      1
14     e      1
15     d      1
16     s      1

In [38]:
df_table ['all'] = 'x'
df_table

   items  count all
0      c      4   x
1      f      4   x
2      a      3   x
3      b      3   x
4      p      3   x
5      m      3   x
6      o      2   x
7      i      2   x
8      h      1   x
9      j      1   x
10     k      1   x
11     l      1   x
12     g      1   x
13     n      1   x
14     e      1   x
15     d      1   x
16     s      1   x

In [39]:
pip install plotly

Collecting plotly
  Downloading plotly-5.11.0-py2.py3-none-any.whl (15.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.3/15.3 MB 51.2 MB/s eta 0:00:0000:0100:01
Collecting tenacity>=6.2.0
  Downloading tenacity-8.1.0-py3-none-any.whl (23 kB)
Installing collected packages: tenacity, plotly
Successfully installed plotly-5.11.0 tenacity-8.1.0
Note: you may need to restart the kernel to use updated packages.

In [42]:
import plotly.express as px
import plotly.io as pio           #thsese two lines to see the graph in mybinder
pio.renderers.default = 'iframe'

In [49]:
fig = px.treemap(df_table,
                 path = ['all', 'items'],
                 values = 'count',
                 color = df_table['count'],
                 color_continuous_scale = 'Blues',
                 hover_data = ['items']
                )
fig.show()

In [51]:
tra = []
for i in range(0, df.shape[0]):
    tra.append([ str(df.values[i,j])
                for j in range (0, df.shape[1])
               ]
              )
tra

[['a', 'c', 'd', 'f', 'g', 'i', 'm', 'p'],
 ['a', 'b', 'c', 'f', 'l', 'm', 'o', 'nan'],
 ['b', 'f', 'h', 'j', 'o', 'nan', 'nan', 'nan'],
 ['b', 'c', 'k', 's', 'p', 'nan', 'nan', 'nan'],
 ['a', 'c', 'e', 'f', 'i', 'p', 'm', 'n']]

In [52]:
pip install mlxtend

Collecting mlxtend
  Downloading mlxtend-0.21.0-py2.py3-none-any.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 18.5 MB/s eta 0:00:0000:010:01
Collecting scikit-learn>=1.0.2
  Downloading scikit_learn-1.0.2-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (24.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.8/24.8 MB 48.5 MB/s eta 0:00:0000:0100:01
Collecting scipy>=1.2.1
  Downloading scipy-1.7.3-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (38.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.1/38.1 MB 18.9 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: numpy>=1.16.2 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from mlxtend) (1.21.6)
Requirement already satisfied: pandas>=0.24.2 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from mlxtend) (1.3.5)
Collecting matplotlib>=3.0.0
  Downloading matplotlib-3.5.3-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (11.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.2/11.2 MB 43.7 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: setuptools in /srv/conda/envs/notebook/lib/python3.7/site-packages (from mlxtend) (65.4.1)
Collecting joblib>=0.13.2
  Downloading joblib-1.2.0-py3-none-any.whl (297 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 298.0/298.0 kB 34.2 MB/s eta 0:00:00
Requirement already satisfied: packaging>=20.0 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from matplotlib>=3.0.0->mlxtend) (21.3)
Collecting cycler>=0.10
  Downloading cycler-0.11.0-py3-none-any.whl (6.4 kB)
Requirement already satisfied: python-dateutil>=2.7 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from matplotlib>=3.0.0->mlxtend) (2.8.2)
Requirement already satisfied: pyparsing>=2.2.1 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from matplotlib>=3.0.0->mlxtend) (3.0.9)
Collecting pillow>=6.2.0
  Downloading Pillow-9.3.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 80.9 MB/s eta 0:00:00:00:01
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.4.4-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 68.9 MB/s eta 0:00:00
Collecting fonttools>=4.22.0
  Downloading fonttools-4.38.0-py3-none-any.whl (965 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 965.4/965.4 kB 61.8 MB/s eta 0:00:00
Requirement already satisfied: pytz>=2017.3 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from pandas>=0.24.2->mlxtend) (2022.4)
Collecting threadpoolctl>=2.0.0
  Downloading threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Requirement already satisfied: typing-extensions in /srv/conda/envs/notebook/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib>=3.0.0->mlxtend) (4.4.0)
Requirement already satisfied: six>=1.5 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)
Installing collected packages: threadpoolctl, scipy, pillow, kiwisolver, joblib, fonttools, cycler, scikit-learn, matplotlib, mlxtend
Successfully installed cycler-0.11.0 fonttools-4.38.0 joblib-1.2.0 kiwisolver-1.4.4 matplotlib-3.5.3 mlxtend-0.21.0 pillow-9.3.0 scikit-learn-1.0.2 scipy-1.7.3 threadpoolctl-3.1.0
Note: you may need to restart the kernel to use updated packages.

In [55]:
from mlxtend.preprocessing import TransactionEncoder

In [57]:
te = TransactionEncoder()
te_ary = te.fit(tra).transform(tra)
encoded_df = pd.DataFrame (te_ary,
                           columns = te.columns_)
encoded_df

,a,b,c,d,e,f,g,h,i,j,k,l,m,n,nan,o,p,s
0,True,False,True,True,False,True,True,False,True,False,False,False,True,False,False,False,True,False
1,True,True,True,False,False,True,False,False,False,False,False,True,True,False,True,True,False,False
2,False,True,False,False,False,True,False,True,False,True,False,False,False,False,True,True,False,False
3,False,True,True,False,False,False,False,False,False,False,True,False,False,False,True,False,True,True
4,True,False,True,False,True,True,False,False,True,False,False,False,True,True,False,False,True,False

In [58]:
encoded_df.drop(['nan'], axis = 1, inplace = True)
encoded_df.columns

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n',
       'o', 'p', 's'],
      dtype='object')

In [59]:
from mlxtend.frequent_patterns import fpgrowth

In [62]:
f_itemsets = fpgrowth(encoded_df,
                     min_support = 0.6,
                     use_colnames = True
                    )
f_itemsets

    support      itemsets
0       0.8           (f)
1       0.8           (c)
2       0.6           (p)
3       0.6           (m)
4       0.6           (a)
5       0.6           (b)
6       0.6        (c, f)
7       0.6        (c, p)
8       0.6        (c, m)
9       0.6        (m, f)
10      0.6     (c, m, f)
11      0.6        (m, a)
12      0.6        (c, a)
13      0.6        (a, f)
14      0.6     (c, m, a)
15      0.6     (m, a, f)
16      0.6     (c, a, f)
17      0.6  (c, m, a, f)

In [63]:
from mlxtend.frequent_patterns import association_rules

In [64]:
a_rules = association_rules(f_itemsets,
                            metric = 'lift',
                            min_threshold = 1.5
                           )
a_rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,"(c, f)",(m),0.6,0.6,0.6,1.0,1.666667,0.24,inf
1,(m),"(c, f)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
2,(m),(a),0.6,0.6,0.6,1.0,1.666667,0.24,inf
3,(a),(m),0.6,0.6,0.6,1.0,1.666667,0.24,inf
4,"(c, m)",(a),0.6,0.6,0.6,1.0,1.666667,0.24,inf
5,"(c, a)",(m),0.6,0.6,0.6,1.0,1.666667,0.24,inf
6,(m),"(c, a)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
7,(a),"(c, m)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
8,"(m, f)",(a),0.6,0.6,0.6,1.0,1.666667,0.24,inf
9,"(a, f)",(m),0.6,0.6,0.6,1.0,1.666667,0.24,inf
10,(m),"(a, f)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
11,(a),"(m, f)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
12,"(c, f)",(a),0.6,0.6,0.6,1.0,1.666667,0.24,inf
13,(a),"(c, f)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
14,"(c, m, f)",(a),0.6,0.6,0.6,1.0,1.666667,0.24,inf
15,"(c, a, f)",(m),0.6,0.6,0.6,1.0,1.666667,0.24,inf
16,"(c, m)","(a, f)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
17,"(c, a)","(m, f)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
18,"(c, f)","(m, a)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
19,"(m, a)","(c, f)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
20,"(m, f)","(c, a)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
21,"(a, f)","(c, m)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
22,(m),"(c, a, f)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
23,(a),"(c, m, f)",0.6,0.6,0.6,1.0,1.666667,0.24,inf